#!/usr/bin/bash

# init 20230124

# resolution in dpi for black/white pages
blackwhiteresolution=600

# resolution in dpi for colored pages
colorresolution=300


if [ $# -lt 1 ] ; then
	echo "make-tifpdf: create a $blackwhiteresolution dpi pdf with 1-bit-tiff black/white or $colorresolution dpi color images for uploading scans to → bitsavers.org"
	echo "Usage: make-tifpdf <infile.pdf> [outfile.pdf]"
	echo
	exit
fi

# tumble source: https://github.com/brouhaha/tumble
# tumble is a utility by Eric Smith to construct PDF files from one or more 1-bit-tiff image files

start=$(date +%s.%N)

# Path to tumble program
tumble="/home/benutzer/src/tumble/tumble"

red="\e[1;31m"
yellow="\e[1;33m"
green="\e[1;32m"
cyan="\e[1;36m"
nocol="\e[0m"

# directory for resulting output files
tumbledir="tumble"
mkdir -p $tumbledir

# directory for processed input files
donedir="done"
mkdir -p $donedir

function ProgressBar {

	# https://raw.githubusercontent.com/fearside/ProgressBar/master/progressbar.sh
	# Author : Teddy Skarin

	# 1. Create ProgressBar function
	# 1.1 Input is currentState($1) and totalState($2)

	# Process data
	let _progress=(${1}*100/${2}*100)/100
	let _done=(${_progress}*4)/10
	let _left=40-${_done}

	# Build progressbar string lengths
	_done=$(printf "%${_done}s")
	_left=$(printf "%${_left}s")

	# 1.2 Build progressbar strings and print the ProgressBar line
	# 1.2.1 Output example:
	# 1.2.1.1 Progress : [########################################] 100%
	printf "\rProgress : [${_done// /#}${_left// /-}] ${_progress}%%"

}

infile=$1

if [ ! -f $infile ]; then
	echo -e "${red}No such file:"
	echo -e "$infile ${nocol}"
	exit
fi

if [ $# -eq 1 ] ; then
	outfile="$tumbledir/${infile%.*}--tumble--${blackwhiteresolution}dpi.pdf"
else
	outfile=$2
fi

if [ -f $outfile ] ; then

	echo "${infile}:"
	echo -e "${green}As the corresponding output file already exists, processing is skipped.${nocol}"

	if [ -f $infile ] ; then
		echo "Thus we simply move the input file to"
		echo "→ $donedir/$infile.done"
		mv "$infile" "$donedir/$infile.done"
	fi

	echo
	exit
fi


tmpdir=$(mktemp -d -t make-tifpdf-XXXXXXXXXX)

numberofpages=$(pdfinfo "$infile" | grep "Pages" | awk '{print $2}')

echo -e "${cyan}Processing:"
echo $(du -h "$infile")
echo -e "$numberofpages PDF pages${nocol}"

lastbutonepage=$(echo "$numberofpages - 1" | bc)

# explode any page in the infile pdf to single 600 dpi ppm file
# each file: filesize 62 MB

let endprogress=$numberofpages*2
let halfprogress=$numberofpages

declare -a rgb

SAVEIFS=$IFS

IFS=$'\n'
# array of pages with rgb
rgb=( $(pdfimages -list "$infile" | awk 'FNR>2 {printf("%06d%s\n", $1, $6) }' | sed -n "s/rgb//p" | uniq ) )
IFS=$SAVEIFS


for (( page = 1; page <= ${numberofpages}; page++ )); do

	ProgressBar $page $endprogress

	printf -v pgnr "%06d" $page

	if [[ " ${rgb[*]} " =~ " ${pgnr} " ]]; then
		pdftoppm -f $page -singlefile -jpeg -r $colorresolution "$infile" $tmpdir/p-${pgnr}
	else
		pdftoppm -f $page -singlefile -r $blackwhiteresolution "$infile" $tmpdir/p-${pgnr}
	fi

done

j=$halfprogress
ppmpages=$(find $tmpdir -name *.ppm | wc -l)

if [ $ppmpages -gt 0 ]; then

	for i in $tmpdir/p*.ppm; do

		let j=$j+1
		ProgressBar $j $endprogress

	#	http://www.fmwconcepts.com/imagemagick/2colorthresh/index.php
	#
	#	2COLORTHRESH automatically thresholds an image to binary (b/w) format using an adaptive spatial subdivision color reduction technique.
	#	This is the -colors IM operator as implemented with slight modification from Anthony's Examples
	#	at http://www.imagemagick.org/Usage/quantize/#two_color
	#
	#	For algorithm details, see http://www.imagemagick.org/script/quantize.php
	#	adapted to output create 1-bit tiff files in the desired resolution

	#	"-colors 2" sometimes produces all black tif pages for all white pages
		convert $i -density $blackwhiteresolution +dither -colors 2 -colorspace gray -contrast-stretch 0 -depth 1 "${i%.*}.tif"
		rm $i

	done
fi

$tumble $(ls $tmpdir/*) -o "$outfile" &>/dev/null

ProgressBar $endprogress $endprogress

end=$(date +%s.%N)
runtime=$(echo "scale=2;($end - $start)/1" | bc)
pagesperminute=$(echo "scale=2;60 * $numberofpages / $runtime" | bc)
secondsperpage=$(echo "scale=2;$runtime / $numberofpages" | bc)

# postprocess infile
# move to $donedir
mv "$infile" "$donedir/$infile.done"

echo
echo $(du -h "$donedir/$infile.done")
echo $(du -h "$outfile")
echo
echo -e "$yellow=== Summary ===$nocol"

echo "$runtime seconds processing time"
echo "PDF: $numberofpages pages"
echo "$pagesperminute pages/minute"
echo "$secondsperpage seconds/page"
echo

# cleaning up

rm -rf $tmpdir
